//
//  APIContant.h
//  KYPFanfou
//
//  Created by trainer on 7/27/16.
//  Copyright © 2016 trainer. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const API_ACCESS_TOKEN;

FOUNDATION_EXPORT NSString *const CONSUMER_KEY;
FOUNDATION_EXPORT NSString *const CONSUMER_SECRET;
FOUNDATION_EXPORT NSString *const FANFOU_BASE_HOST ;
FOUNDATION_EXPORT NSString *const FANFOU_API_HOST;
FOUNDATION_EXPORT NSString *const API_VERIFY_CREDENTIALS;
FOUNDATION_EXPORT NSString *const API_VERIFY_CREDENTIALS;
FOUNDATION_EXPORT NSString *const API_HOME_TIMELINE;
FOUNDATION_EXPORT NSString *const API_UPDATE_TEXT;
FOUNDATION_EXPORT NSString *const API_UPLOAD_PHOTO;
FOUNDATION_EXPORT NSString *const API_FAVORITES_CREATE;
FOUNDATION_EXPORT NSString *const API_CONVERSATION_LIST;
FOUNDATION_EXPORT NSString *const API_CONVERSATION;
FOUNDATION_EXPORT NSString *const API_MESSAGES_NEW;
FOUNDATION_EXPORT NSString *const API_PHOTOS_TIMELINE;
FOUNDATION_EXPORT NSString *const API_UPDATE_PROFILE_IMAGE;
FOUNDATION_EXPORT NSString *const API_UPDATE_PROFILE;
FOUNDATION_EXPORT NSString *const API_TRENDS_LIST;
FOUNDATION_EXPORT NSString *const API_SEARCH_PUBLIC_TIMELINE;
FOUNDATION_EXPORT NSString *const API_USERS_SHOW ;
FOUNDATION_EXPORT NSString *const API_STATUSES_USER_TIMELINE;
FOUNDATION_EXPORT NSString *const API_FRIENDSHIPS_CREATE;
FOUNDATION_EXPORT NSString *const API_FRIENDSHIPS_DESTROY;










